# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ContentEncoder": "AdaptiveUnet.ipynb",
         "StyleEncoder": "AdaptiveUnet.ipynb",
         "get_adastats": "AdaptiveUnet.ipynb",
         "AdaIN": "AdaptiveUnet.ipynb",
         "AdaSkipBlock": "AdaptiveUnet.ipynb",
         "AdaResBlock": "AdaptiveUnet.ipynb",
         "Decoder": "AdaptiveUnet.ipynb",
         "UnetBlock": "BaseBlocks.ipynb",
         "UpBlock": "BaseBlocks.ipynb",
         "UpResBlock": "BaseBlocks.ipynb",
         "Conv2dBlock": "BaseBlocks.ipynb",
         "LayerNorm": "BaseBlocks.ipynb",
         "ResBlock": "BaseBlocks.ipynb",
         "ResBlocks": "BaseBlocks.ipynb",
         "conv_and_res": "BaseBlocks.ipynb",
         "DisResBlock": "BaseBlocks.ipynb",
         "OptimizedBlock": "BaseBlocks.ipynb",
         "DoubleImage": "DataBunch.ipynb",
         "DoubleImageList": "DataBunch.ipynb",
         "ProjectionDiscriminator": "Discrminators.ipynb",
         "UnconditionalDiscriminator": "Discrminators.ipynb",
         "mse": "Losses.ipynb",
         "cov": "Losses.ipynb",
         "one_norm": "Losses.ipynb",
         "get_adv_loss": "Losses.ipynb",
         "get_rec_loss": "Losses.ipynb",
         "get_latent_loss": "Losses.ipynb",
         "get_sdist_loss": "Losses.ipynb",
         "bce": "Losses.ipynb",
         "get_seg_loss": "Losses.ipynb",
         "HiDTLoss": "Losses.ipynb",
         "HiDT": "Training.ipynb",
         "HiDTModule": "Training.ipynb",
         "HiDTTrainer": "Training.ipynb",
         "FixedGANSwitcher": "Training.ipynb"}

modules = ["adaptive_unet.py",
           "building_blocks.py",
           "data_bunch.py",
           "discriminators.py",
           "losses.py",
           "training.py"]

doc_url = "https://BradleyBrown19.github.io/HiDT/"

git_url = "https://github.com/BradleyBrown19/HiDT/tree/master/"

def custom_doc_links(name): return None
