# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ContentEncoder": "AdaptiveUnet.ipynb",
         "StyleEncoder": "AdaptiveUnet.ipynb",
         "get_adastats": "AdaptiveUnet.ipynb",
         "AdaIN": "AdaptiveUnet.ipynb",
         "AdaSkipBlock": "AdaptiveUnet.ipynb",
         "AdaResBlock": "AdaptiveUnet.ipynb",
         "Decoder": "AdaptiveUnet.ipynb",
         "UnetBlock": "BaseBlocks.ipynb",
         "UpBlock": "BaseBlocks.ipynb",
         "UpResBlock": "BaseBlocks.ipynb",
         "Conv2dBlock": "BaseBlocks.ipynb",
         "LayerNorm": "BaseBlocks.ipynb",
         "ResBlock": "BaseBlocks.ipynb",
         "ResBlocks": "BaseBlocks.ipynb",
         "conv_and_res": "BaseBlocks.ipynb",
         "DoubleImage": "DataBunch.ipynb",
         "DoubleImageList": "DataBunch.ipynb",
         "UnconditionalDiscriminator": "LSGAN_Discriminator.ipynb",
         "kl_divergence": "Losses.ipynb",
         "disc_loss": "Losses.ipynb",
         "gen_loss": "Losses.ipynb",
         "HiDT": "TrainLoop.ipynb",
         "GANModule": "TrainLoop.ipynb",
         "GANTrainer": "TrainLoop.ipynb",
         "FixedGANSwitcher": "TrainLoop.ipynb"}

modules = ["adaptive_unet.py",
           "building_blocks.py",
           "data_bunch.py",
           "discriminator.py",
           "losses.py",
           "train_loop.py"]

doc_url = "https://BradleyBrown19.github.io/HiDT/"

git_url = "https://github.com/BradleyBrown19/HiDT/tree/master/"

def custom_doc_links(name): return None
